### ISSUE TITLE
Support web services options in FDSN fetcher

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#454]
Currently, the FDSN fetcher only supports fetching data based on distance from the epicenter. There are use cases where we want to fetch data within a specific bounding box, for example CVM development.

Because we convert the config file to a dictionary and we can pass arguments to the underlying implementation (e.g., obspy FDSN client), it would be relatively easy to support all FDSN web services options for retrieving stations. I think the only tricky part is the high-level parameters like time before P wave arrival and time after (possible solution: strip from copy of dictionary and replace with FDSN keys/values derived from those). For most settings we can just use the FDSN web services key/value pairs in the YAML config file.

## Example 1: Update of current keys/values to match FDSN

```yaml
FDSNFetcher:
    maxradius : 0.3 # Match FDSN key
    time_before : 30 # No matching FDSN key
    time_after : 30 # No matching FDSN key
    channels : ["BH?", "HH?", "BN?", "HN?"]
```

## Example 2: Bounding box

```yaml
FDSNFetcher:
    minlatitude: 34.5
    maxlatitude: 35.5
    minlongitude: -122.0
    maxlongitude: -120.0
    time_before : 30 # No matching FDSN key
    time_after : 30 # No matching FDSN key
    channels : ["BH?", "HH?", "BN?", "HN?"]
```
